build-batctl: abort if build failed

diff --git a/build-batctl b/build-batctl
--- a/build-batctl
+++ b/build-batctl
@@ -93,5 +93,9 @@ if [ "$1" = "check" ]; then
 else
 	prepare
 	build
+	if [ "$?" != "0" ]; then
+		echo "build may have failed."
+		exit 1
+	fi
 	install
 fi
